version: '3.8'
services:
  mysqldb:
    image: mysql:8
    restart: unless-stopped
    env_file: ./api/.env 
    environment:
      - MYSQL_ROOT_PASSWORD=mysql123
      - MYSQL_DATABASE=mfs 
    ports:
      - 3306:3306
    volumes:
      - db:/var/lib/mysql
  
  # phpmyadmin:
  #   image: phpmyadmin/phpmyadmin
  #   container_name: pma
  #   links:
  #     - mysqldb
  #   environment:
  #     PMA_HOST: mysqldb
  #     PMA_PORT: 3306
  #     PMA_ARBITRARY: 1
  #   restart: always
  #   ports:
  #     - 3307:80
      
  api:
    depends_on:
      - mysqldb
    build:
      context: ./api
    ports:
      - 3000:3000
    volumes:
      - ./api:/app
    env_file: ./api/.env
    environment:
      - DB_HOST=mysqldb 
    stdin_open: true

  backoffice:
    build:
      context: ./backoffice
    ports:
      - 8080:8080
    volumes:
      - ./backoffice:/app
    
  website:
    build:
      context: ./website
    ports:
      - 8000:8000
    volumes:
      - ./website:/app

  template:
    build:
      context: ./website-template
    ports:
      - 8001:80
    volumes:
      - ./website-template:/usr/share/nginx/html
volumes: 
  db: