CREATE TABLE users (
    id	        	INTEGER	PRIMARY KEY,
	username    	VARCHAR(50) UNIQUE NOT NULL,
    password    	VARCHAR(100) NOT NULL,
	email       	VARCHAR(100) UNIQUE NOT NULL,
	observations	TEXT NULL,
	status			ENUM('AC', 'BA') DEFAULT 'AC',
	created_at  	TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 	updated_at  	TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);