CREATE TABLE categories (
    id				INTEGER	PRIMARY KEY,
    description 	VARCHAR(100) NOT NULL,
	slug			VARCHAR(150) NOT NULL,
	created_at 		TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 	updated_at 		TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
