CREATE TABLE products (
    id				BIGINT	PRIMARY KEY,
    category_id		INTEGER,
	title 			VARCHAR(100) NOT NULL,
	slug			VARCHAR(150) UNIQUE NOT NULL,
    description 	VARCHAR(512) NULL,
	price_cost		NUMERIC(18,2) NOT NULL DEFAULT 0.00,
	price_public 	NUMERIC(18,2) NOT NULL DEFAULT 0.00,
	created_at 		TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 	updated_at 		TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

	FOREIGN KEY (category_id) REFERENCES categories(id) ON DELETE SET NULL
);
