CREATE TABLE products_images (
    id			BIGINT	PRIMARY KEY,
    product_id	BIGINT,
	description	VARCHAR(50) UNIQUE NOT NULL,
	base64		BLOB NOT NULL,
	created_at 	TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 	updated_at 	TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 
	FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE
);
 