CREATE TABLE images (
    id			BIGINT	PRIMARY KEY,
    product_id	BIGINT NOT NULL,
	filename	VARCHAR(50) NULL,
	type		CHAR(5) NULL,
	description	VARCHAR(50) NULL,
	base64		BLOB NOT NULL,
	created_at 	TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 	updated_at 	TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
 