CREATE TABLE products (
    id				BIGINT	PRIMARY KEY,
	title 			VARCHAR(100) NOT NULL,
	slug			VARCHAR(150) UNIQUE NOT NULL,
    description 	VARCHAR(512) NULL,
	price_cost		NUMERIC(18,2) NOT NULL DEFAULT 0.00,
	price_public 	NUMERIC(18,2) NOT NULL DEFAULT 0.00,
	status			ENUM('AC', 'BA') DEFAULT 'AC',
	observations	TEXT NULL,
	created_at 		TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 	updated_at 		TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
