
import { Brand } from "src/models/entities/Brand.entity";

export const brandFactory: Partial<Brand>[] = [
    { description: "Apple" },
    { description: "Samsung" },
    { description: "Amazon" },
    { description: "Microsoft" },
    { description: "Google" },
    { description: "Facebook" },
    { description: "Coca-Cola" },
    { description: "Toyota" },
    { description: "McDonald's" },
    { description: "Disney" },
    { description: "Nike" },
    { description: "Adidas" },
    { description: "IBM" },
    { description: "Sony" },
    { description: "Intel" },
    { description: "BMW" },
    { description: "Mercedes-Benz" },
    { description: "Volkswagen" },
    { description: "Louis Vuitton" },
    { description: "H&M" },
    { description: "Zara" },
    { description: "Pepsi" },
    { description: "Nestlé" },
    { description: "General Electric" },
    { description: "HP" },
    { description: "Canon" },
    { description: "L'Oreal" },
    { description: "Gillette" },
    { description: "Colgate" },
    { description: "Nokia" }, 
    { description: "Oracle" },
    { description: "Netflix" },
    { description: "Uber" },
    { description: "Airbnb" },
    { description: "PayPal" },
    { description: "Visa" },
    { description: "Mastercard" },
    { description: "American Express" },
    { description: "Burger King" },
    { description: "KFC" },
    { description: "Starbucks" },
    { description: "Tesla" },
    { description: "Lamborghini" },
    { description: "Ferrari" },
    { description: "Rolex" },
    { description: "Tiffany & Co." },
    { description: "Prada" },
    { description: "Gucci" },
    { description: "Chanel" },
    { description: "Hermès" },
    { description: "Cartier" },
    { description: "Porsche" },
    { description: "Dior" },
    { description: "Goodyear" },
    { description: "IKEA" },
    { description: "Honda" },
    { description: "Mitsubishi" },
    { description: "Lexus" },
    { description: "Panasonic" },
    { description: "Dell" },
    { description: "Lenovo" },
    { description: "WhatsApp" },
    { description: "Twitter" },
    { description: "Instagram" },
    { description: "Snapchat" },
    { description: "LinkedIn" },
    { description: "Pinterest" },
    { description: "Spotify" },
    { description: "Adobe" },
    { description: "TikTok" },
    { description: "Skype" },
    { description: "Slack" },
    { description: "Zoom" },
    { description: "PlayStation" },
    { description: "Xbox" },
    { description: "Nintendo" }, 
    { description: "GoPro" },
    { description: "GoDaddy" },
    { description: "Red Bull" },
    { description: "Vodafone" },
    { description: "Verizon" },
    { description: "AT&T" }, 
    { description: "LG" },
    { description: "Philips" },
    { description: "Siemens" },
    { description: "Bosch" },
    { description: "Nivea" },
    { description: "Dove" },
    { description: "Oreo" },
    { description: "Kellogg's" },
    { description: "Lays" },
    { description: "Heinz" },
    { description: "Nutella" },
    { description: "Cadbury" },
    { description: "Fanta" },
    { description: "Sprite" },
    { description: "Walmart" },
    { description: "Target" },
    { description: "Best Buy" },
    { description: "Costco" },
    { description: "Home Depot" },
    { description: "Lowe's" },
    { description: "Walgreens" },
    { description: "CVS" },
    { description: "FedEx" },
    { description: "UPS" }
];
