
import { Characteristic } from "src/models/entities/Characteristic.entity";

export const characteristicFactory: Partial<Characteristic>[] = [
    { title: 'Tamaño', description: 'Tamaño (texto)', abbreviation: 'Tam.', isString: true, isNumber: false },
    { title: 'Tamaño', description: 'Tamaño (número)', abbreviation: 'Tam.', isString: true, isNumber: false },
    { title: 'Talle', description: 'Talle (texto)', abbreviation: 'Talle', isString: true, isNumber: false },
    { title: 'Talle', description: 'Talle Arg (número) ', abbreviation: 'Talle', suffix: 'Arg' },
    { title: 'Talle', description: 'Talle US (número) ', abbreviation: 'Talle', suffix: 'US' },
    { title: 'Talle', description: 'Talle UK (número) ', abbreviation: 'Talle', suffix: 'UK' },
    { title: 'Talle', description: 'Talle EUR (número) ', abbreviation: 'Talle', suffix: 'EUR' },
    { title: 'Talle', description: 'Talle centimetros ', abbreviation: 'Talle', suffix: 'cm' },
    { title: 'Largo', description: 'Centímetros (largo)', abbreviation: 'Largo', suffix: 'cm' },
    { title: 'Ancho', description: 'Centímetros (ancho)', abbreviation: 'Ancho', suffix: 'cm' },
    { title: 'Altura', description: 'Centímetros (altura)', abbreviation: 'Alt.', suffix: 'cm' },
    { title: 'Espesor', description: 'Centímetros (espesor)', abbreviation: 'Esp.', suffix: 'cm' },
    { title: 'Largo', description: 'Milímetros (largo)', abbreviation: 'Largo', suffix: 'mm' },
    { title: 'Ancho', description: 'Milímetros (ancho)', abbreviation: 'Ancho', suffix: 'mm' },
    { title: 'Altura', description: 'Milímetros (altura)', abbreviation: 'Alt.', suffix: 'mm' },
    { title: 'Espesor', description: 'Milímetros (espesor)', abbreviation: 'Esp.', suffix: 'mm' },
    { title: 'Largo', description: 'Metros (largo)', abbreviation: 'Largo', suffix: 'm.' },
    { title: 'Ancho', description: 'Metros (ancho)', abbreviation: 'Ancho', suffix: 'm.' },
    { title: 'Altura', description: 'Metros (altura)', abbreviation: 'Alt.', suffix: 'm.' },
    { title: 'Espesor', description: 'Metros (espesor)', abbreviation: 'Esp.', suffix: 'm.' },
    { title: 'Capacidad', description: 'Litro', abbreviation: 'Cap.', suffix: 'l.' },
    { title: 'Capacidad', description: 'Mililitro', abbreviation: 'Cap.', suffix: 'ml.' },
    { title: 'Autonomía', description: 'Autonomía en mililitros', abbreviation: 'Auto.', suffix: 'ml.' },
    { title: 'Autonomía', description: 'Autonomía en litros', abbreviation: 'Auto.', suffix: ' l.' },
    { title: 'Con control remoto', description: 'Con control remoto', isCheck: true, isNumber: false },
    { title: 'Con respaldo', description: 'Con respaldo', isCheck: true, isNumber: false },
    { title: 'Con WiFi', description: 'Con WiFi', isCheck: true, isNumber: false },
    { title: 'Potencia máxima', description: 'Potencia máxima', abbreviation: 'P.Max.', suffix: ' W' },
    { title: 'Nro. Serie', description: 'Nro. Serie', isString: true, isNumber: false },
    { title: 'Material', description: 'Material', isString: true, isNumber: false },
    { title: 'Color', description: 'Color', isString: true, isNumber: false },
    { title: 'Modelo', description: 'Modelo', isString: true, isNumber: false },
]